config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/players' => 'players#index'

  get '/players/new'=>'players#new'


  get '/players/:id' => 'players#show', as: :player

  get '/players/:id/edit' => 'players#edit' , as: :edit_player

  patch '/players/:id' => 'players#update'

  post 'players' => 'players#create'


  resources :players do
    resources :transfers
  end

  get '/players/:player_id/transfers' => 'transfers#index'

  get '/players/:player_id/transfers/new' =>'transfers#new'

  post '/players/:player_id/transfers' => 'transfers#create'

  get 'weathers' => 'weathers#index'


  resources :weathers do
    resources :raffles
  end

  get 'raffles' => 'raffles#home'

  get '/weathers/:weather_id/raffles' => 'raffles#index'

#  get '/weathers/:weather_id/raffles/:id' => 'raffles#show' , as: :raffle

  get '/weathers/:weather_id/raffles/new' => 'raffles#new'

  post '/weathers/:weather_id/raffles' => 'raffles#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :player
  belongs_to :raffle
  def self.pay_bet(bet)
    @player=bet.player
    @raffle=bet.raffle
    transfer_amount=0

    if(@raffle.color==bet.bet_color&&bet.bet_color=="verde")
      transfer_amount=bet.bet_amount.to_i*14
    elsif(@raffle.color==bet.bet_color)
      transfer_amount=bet.bet_amount.to_i
    else
      transfer_amount=bet.bet_amount.to_i*(-1)

    end
    @transfer=@player.transfers.create({amount:transfer_amount})

  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :bets
  has_many :raffles, through: :bets
  has_many :transfers
end

app/models/raffle.rb
class Raffle < ApplicationRecord
  has_many :bets
  has_many :players, through: :bets
  belongs_to :weather

  def self.random_color
    nrandom=rand(99)
    if nrandom==0||nrandom==1
      color='verde'
    elsif nrandom>1&& nrandom<50
      color='rojo'
    else
      color='negro'
    end
    color
  end

  def self.all_raffle_process
    @weather=Weather.forecast_today()

    color=Raffle.random_color()
    @raffle=Raffle.create({color:color,weather:@weather})
    @players=Player.all

    @players.each do |player|
      color=Raffle.random_color()


      @transfers=player.transfers
      bet_amount=Transfer.calc_bet_amount(@transfers)
      if bet_amount>0
        @bet=@raffle.bets.create({bet_color:color,bet_amount:bet_amount, player:player})
        Bet.pay_bet(@bet)
        #@transfer=Transfer.create({amount:"10074",player:player})


      end
    end
  end
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :player
  def self.balance(transfers)
    total=0
    transfers.each do |transfer|
      total+=transfer.amount.to_i
    end
    total
  end

  def self.transfer_to_all
    players=Player.all
    players.each do |player|
      Transfer.create({amount:"10000",player:player})
    end
  end

  def self.calc_bet_amount(transfers)
    total=self.balance(transfers)
    weather=Weather.forecast_today()
    temp=weather.nil? ? nil : weather.forecast_temp
    bet_amount=0
    nrandom=rand(99)

    if  total==0
      bet_amount=0
    elsif total<=1000
      betamount=total
    elsif temp<=29
      percentage=(7.0/99.0)*nrandom+8
      factor=percentage/100.0
      bet_amount=total*factor
    elsif temp>29
      percentage=(4.0/99.0)*nrandom+3
      factor=percentage/100.0
      bet_amount=total*factor
    elsif temp.nil
      puts "Ocurrió un error con la temperatura"

    end
    bet_amount
    end

end

app/models/weather.rb
class Weather < ApplicationRecord
  has_many:raffles
  def self.forecast_from_api
    headers = {
      'x-rapidapi-host' => "community-open-weather-map.p.rapidapi.com",
      'x-rapidapi-key' => "a402c1becdmsh32280587dc0cc5fp1942ccjsna72e3da74bdb"
  }

  url = 'https://community-open-weather-map.p.rapidapi.com/climate/month'
  params = '?q=Santiago'
  response = HTTParty.get(url+params,
    :headers => headers
  )

    logger.info "Mostrando json #{response.parsed_response["list"][7]["dt"]}"
    forecast_temp=response.parsed_response["list"][7]["temp"]["average_max"].to_f-273.15
    forecast_date=response.parsed_response["list"][7]["dt"]
    return Weather.create(forecast_date:Time.at(forecast_date),forecast_temp:forecast_temp)
    #puts response.read_body
    #Weather.create(forecast_date:json[7].dt)
  end
  def self.forecast_today
    date=Time.now
    weathers=Weather.all
    finded=false

    weathers.each do |weather|
      if(weather.created_at.day==date.day&&weather.created_at.month==date.month&&weather.created_at.year==date.year)
        finded=true
        return weather
      end
    end

    return self.forecast_from_api()

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  def create
    @player=Player.find(params[:player_id])
    @raffle=Raffle.find(params[:raffle_id])
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players=Player.all
  end
  def show
    @player=Player.find(params[:id])
    @raffles=@player.raffles
    @bets=@player.bets
    @transfer=@player.transfers
  end
  def new
    @player=Player.new
  end
  def create
    @player=Player.new(player_params)
    @transfer=@player.transfers.build({amount:"10000"})

    if @player.save

      redirect_to '/players'
    else
      render '/new'
    end
  end
  def edit
    @player=Player.find(params[:id])

  end
  def update
    @player=Player.find(params[:id])
    if @player.update(player_params)
      redirect_to(:action => 'show',:id => @player.id)
    else
      render 'edit'
    end
  end
  private
  def player_params
    params.require(:player).permit(:first_name,:last_name,:rut)
  end



end

app/controllers/raffles_controller.rb
class RafflesController < ApplicationController
  def index
    @weather=Weather.find(params[:weather_id])
    @raffles=@weather.raffles
  end
  def home
    @raffles=Raffle.all
  end

  def new
    @weather=Weather.find(params[:weather_id])
    @raffle=Raffle.new

  end

  def create
    @weather=Weather.find(params[:weather_id])

    color=Raffle.random_color()
    @raffle=Raffle.create({color:color,weather:@weather})
    @players=Player.all

    @players.each do |player|
      color=Raffle.random_color()


      @transfers=player.transfers
      bet_amount=Transfer.calc_bet_amount(@transfers)
      if bet_amount>0
        @bet=@raffle.bets.create({bet_color:color,bet_amount:bet_amount, player:player})
        Bet.pay_bet(@bet)
        #@transfer=Transfer.create({amount:"10074",player:player})


      end
    end

    if @raffle.save
      redirect_to(controller:'raffles', action:'index',id:@weather.id)
    else
      render '/new'
    end
  end



  private
  def raffle_params
    params.require(:raffle).permit(:color)
  end

end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
def index
  @player=Player.find(params[:player_id])
  @transfers=@player.transfers
end
def new
  @player=Player.find(params[:player_id])
  @transfer=Transfer.new
end


def create
  @player=Player.find(params[:player_id])
  @transfer=@player.transfers.build(transfer_params)
  if @transfer.save
    redirect_to(:action=>'index',:id=>@player.id)
  else
    render 'new'

  end
end

private
def transfer_params
  params.require(:transfer).permit(:amount)
end

end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
def index
  @weathers=Weather.all
end
def show
  @weather=Weather.find(params[:id])
  @raffles=@weather.raffles
  
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bet_helper.rb
module BetHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/raffles_helper.rb
module RafflesHelper
end

app/helpers/wallet_status_helper.rb
module WalletStatusHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TareaNnodes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<div class="header">
  <div class="container">
    <%= image_tag ("ruleta.png") %>
  </div>
</div>

<div class="destination">
  <div class="container">


    <!-- Your code here -->
    <%= form_for(@player) do |p| %>
  <div class="name">
    <%= p.label :nombre %>
    <%= p.text_field :first_name %><br>
    <%= p.label :apellido %>
    <%= p.text_field :last_name %>
    <%= p.label :rut %>
    <%= p.text_field :rut %>

  </div>
  <div class="actions">
    <%= p.submit "Edit" %>
  </div>
<% end %>

  </div>
</div>

app/views/players/index.html.erb
<div class="header">
  <div class="container">
    <%= image_tag ("ruleta.png") %>

  </div>
</div>

<div class="main">
  <div class="players">
    <div class="container">
  <h2>Players</h2>

    <!--
    To do: Loop through movies and display each one with this HTML
    <div class="movie">
      movie image goes here

      <h3> movie title goes here </h3>
      <p> movie release year goes here </p>
    </div>
    -->
    <% @players.each do |p| %>
      <div class="player">
        <h3><%= p.first_name %> <%= p.last_name %></h3>
        <%= link_to "Ver", player_path(p) %>
          <%= link_to "Edit" , edit_player_path(p) %>
          <%= link_to "Transfer" , player_transfers_path(p) %>

      </div>

    <% end %>
    <div class="actions">
        <%= link_to "New Player", '/players/new' %>

    </div>

    </div>
  </div>

</div>

app/views/players/new.html.erb
<div class="header">
  <div class="container">
    <%= image_tag ("ruleta.png") %>
    <h1>Player</h1>
  </div>
</div>

<div class="players">
  <div class="container">

    <!-- Your code here -->
   <%= form_for(@player) do |p| %>
  <div class="field">
    <%= p.label :nombre %>
    <%= p.text_field :first_name %>
    <%= p.label :apellido %>
    <%= p.text_field :last_name %>
    <%= p.label :rut %>
    <%= p.text_field :rut %>
  </div>
  <div class="actions">
    <%= p.submit "Crear" %>
  </div>
<% end %>


  </div>
</div>

app/views/players/show.html.erb
<div class="header">
  <div class="container">
    <%= image_tag ("ruleta.png") %>

  </div>
</div>
<div class="main">
  <div class="container">


      <h2>Jugador</h2>
      <div class="player">
        <!-- movie image -->
        <h3 class="player-name"><%= @player.first_name%> <%= @player.last_name%> <%= @player.rut%>  </h3>
        <%= link_to "Edit" , edit_player_path(@player) %>
      </div>


    <h2>Raffles</h2>
    <!-- Display each actor's info here -->

    <div class="raffles">
          <% @player.bets.each do |r|%>
            <div class="raffle">
              <h3 class="color">Ruleta: <%=r.raffle.color%> Apuesta:$ <%=r.bet_amount%> Color:<%=r.bet_color%></h3>

            </div>

        <% end %>
    </div>










  </div>
</div>

app/views/raffles/home.html.erb
<div class="header">
  <div class="container">
    <%= image_tag ("ruleta.png") %>

  </div>
</div>

<div class="main">
  <div class="container">
    <div class="raffles">
      <h1>Raffles</h1>
      <% @raffles.each do |r| %>
        <div class="raffle">
          <h2>Ruleta: <%= r.color %> </h2>
            <% r.bets.each do |b| %>

                <h3> Apuesta: $<%= b.bet_amount %> Color: <%= b.bet_color %> Jugador: <%= b.player.first_name %> <%= b.player.last_name %></h3>


            <% end %>
            <p><%= r.created_at %></p>
        </div>
      <% end %>
    </div>



  </div>

</div>

app/views/raffles/index.html.erb
<div class="hero">
  <div class="container">
    <h2>Ruleta de Colores</h2>
    <p> Jugar apostando a colores</p>
    <a href="#">Read More</a>
  </div>
</div>

<div class="main">
  <div class="container">

    <div class="info">
      <!-- movie image -->
      <h3 class="player-name"><%= @weather.forecast_date%> </h3>
      <p class="player-rut"> <%= @weather.created_at%> </p>
      <p class="player-rut"> <%= @weather.forecast_temp%> </p>

    </div>

  </div>


  <h2>Raffles</h2>

    <!--
    To do: Loop through movies and display each one with this HTML
    <div class="movie">
      movie image goes here

      <h3> movie title goes here </h3>
      <p> movie release year goes here </p>
    </div>
    -->
    <%= @raffles.each do |r| %>
      <div class="raffle">
        <h3><%= r.color %> </h3>
      </div>

    <% end %>
    <%= link_to "Create", new_weather_raffle_path(@weather) %>

  </div>
</div>

app/views/raffles/new.html.erb
<div class="header">
  <div class="container">
    <img src="https://content.codecademy.com/courses/learn-rails/img/logo-1m.svg">
    <h1>Player</h1>
  </div>
</div>

<div class="raffles">
  <div class="container">

    <!-- Your code here -->
   <%= form_for [@weather,@raffle] do |f| %>
      <div class="field">
        <%= f.hidden_field :weather_id , :value=>params[:weather_id] %>

      </div>
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>


  </div>
</div>

app/views/transfers/index.html.erb
<div class="header">
  <div class="container">
    <%= image_tag ("ruleta.png") %>

  </div>
</div>
<div class="main">
  <div class="container">
    <h2>Jugador</h2>
    <div class="player">
      <div class="info">
        <!-- movie image -->
        <h2 class="player-name"><%= @player.first_name%> <%= @player.last_name%> <%= @player.rut%>  </h2>
        <%= link_to "Edit" , edit_player_path(@player) %>
      </div>
    </div>


    <h2>Wallet Transfers</h2>
    <!-- Display each actor's info here -->

      <div class="transfers">
        <% @transfers.each do |w|%>
        <div class="raffle">
          <h3 class="color">$<%=w.amount%></h3>
          <p> <%=w.created_at%></p>

        </div>
      <% end %>
        <h1>Balance:$ <%=Transfer.balance(@transfers) %></h1>
        <div class="actions">
          <%= link_to "New Transfer" , new_player_transfer_path(@player) %>

        </div>
      </div>





  </div>
</div>

app/views/transfers/new.html.erb
<div class="header">
  <div class="container">
    <img src="https://content.codecademy.com/courses/learn-rails/img/logo-1m.svg">
    <h1>Player</h1>
  </div>
</div>

<div class="players">
  <div class="container">

    <!-- Your code here -->
    <%= form_for [@player, @transfer] do |f| %>
   <div class="field">
     <%= f.hidden_field :player_id , :value=>params[:player_id] %>
     <%= f.label :amount %><br />
     <%= f.text_field :amount %>
   </div>

   <div class="actions">
     <%= f.submit "Create" %>
   </div>

 <% end %>



  </div>
</div>

app/views/weathers/index.html.erb
<div class="hero">
  <div class="container">
    <h2>Ruleta de Colores</h2>
    <p> Jugar apostando a colores</p>
    <a href="#">Read More</a>
  </div>
</div>

<div class="main">
  <div class="container">
    
  <h2>Weather Forecasts</h2>

    <!--
    To do: Loop through movies and display each one with this HTML
    <div class="movie">
      movie image goes here

      <h3> movie title goes here </h3>
      <p> movie release year goes here </p>
    </div>
    -->
    <%= @weathers.each do |w| %>
      <div class="weather">
        <h3><%= w.forecast_date %> <%= w.forecast_temp %> <%= w.created_at %></h3>
      </div>

    <% end %>

  </div>
</div>